# Generated by Django 4.2.11 on 2025-01-15 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('love', '0004_articulos2_reseña2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña2',
            old_name='comentario',
            new_name='reseña',
        ),
        migrations.AddField(
            model_name='reseña2',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
