# Generated by Django 4.2.11 on 2025-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
