# Generated by Django 4.2.11 on 2025-01-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0007_alter_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
